name: Deploy Project

on:
  workflow_dispatch:
  push:
    branches:
      - deploy_git

jobs:
  deploy_front:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Ensure SSH directory exists
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add SSH known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: .env setting
        working-directory: ./wansungmoon_team
        run: |
          echo REACT_APP_KAKAOKEY=${{ secrets.REACT_APP_KAKAOKEY }} >> .env
          echo REACT_APP_KAKAO_API=${{ secrets.REACT_APP_KAKAO_API }} >> .env
          echo "REACT_APP_HOST=${{ secrets.REACT_APP_HOST }}" >> .env
          echo "REACT_APP_SERVER=${{ secrets.REACT_APP_SERVER }}" >> .env

      - name: Install Dependencies of Front
        working-directory: ./wansungmoon_team
        run: npm i

      - name: Build Front
        working-directory: ./wansungmoon_team
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wansungmoon_team/build

  deploy_back:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Ensure SSH directory exists
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add SSH known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Install Dependencies of Back
        working-directory: ./back
        run: npm i

      - name: Build Back
        working-directory: ./back
        run: npx tsc

      - name: Copy Files to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            rm -rf /var/www/teamproject2
            mkdir /var/www/teamproject2
            mkdir /var/www/teamproject2/uploads'
          rsync -avz -e "ssh" ./back/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/teamproject2/
          rsync -avz -e "ssh" ./back/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/teamproject2/package.json
          rsync -avz -e "ssh" ./back/uploads/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/teamproject2/uploads
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || {
          echo "nvm.sh not found"
          exit 1
          }

          nvm use --lts
          cd /var/www/teamproject2
          npm i --production
          ${{ secrets.SERVER_ENV }}'

      - name: Start Server
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || {
          echo "nvm.sh not found"
          exit 1
          }

          nvm use --lts
          npm install -g pm2
          pm2 delete teamproject2
          pm2 start /var/www/teamproject2/index.js --name teamproject2'
